Algoritmo "Expressoes Aritmeticas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Aprendendo expressoes aritmeticas no Visualg
// Autor(a)    : Walter Teixeira
// Data atual  : 19/02/2026
Var
// + = adição
// - = subtração
// * = multiplicação
// / = divisão
// \ = divisão inteiora
// % ou mod = resto da divisão
// ^ = potenciação
   x: real    y:real    z: real
Inicio

   x <- 12 + 9
   y <- 29
   z <- 44
   
   escreva (x+z/y)

Fimalgoritmo