Algoritmo "Soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Fazer o programar receber e somar dois valores.
// Data atual  : 21/02/2026
Var

  x , y, resultado : inteiro
  
Inicio

   escreva (" Digite o valor de x: ")
   leia (x)
   escreva (" Digite o valor de Y: ")
   leia (y)
   
   resultado <- x + y
   
   escreval (" Soma = ", resultado)
   



Fimalgoritmo